# fly.toml app configuration file generated for damp-leaf-2150 on 2023-07-10T13:51:43-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-leaf-2150"
primary_region = "den"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
